version: 1

trail:
  attestations:
    - name: pull-request
      type: pull_request
  artifacts:
    - name: runner
      attestations:
        - name: rubocop-lint
          type: junit
        - name: unit-test
          type: junit
        - name: unit-test-metrics
          type: custom:test-metrics
        - name: unit-test-coverage-metrics
          type: custom:coverage-metrics
        - name: integration-test
          type: junit
        - name: integration-test-branch-coverage
          type: generic
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan
          type: snyk
