version: 1

trail:
  artifacts:
    - name: runner
      attestations:
        - name: branch-coverage
          type: generic
        - name: snyk-container-scan
          type: snyk
        - name: snyk-code-scan
          type: snyk
