AllCops:
    NewCops: enable

Style/FrozenStringLiteralComment:
  Exclude:
    - code/gnu_zip.rb
    - code/tarfile_writer.rb
    - test/test_base.rb

Lint/PercentStringArray:
  Exclude:
    - test/**/*

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - code/**/*
    - client/code/**/*
    - test/**/*

# I often give an inline expression a name for readability
Lint/UselessAssignment:
  Exclude:
    - code/**/*
    - test/**/*

Naming/VariableNumber:
  Exclude:
    - test/**/*

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - test/server/run_timed_out_test.rb

Style/Documentation:
  Exclude:
    - code/**/*
    - client/code/**/*
    - test/**/*

Metrics/ParameterLists:
  Exclude:
    - code/runner.rb

Lint/EmptyBlock:
  Exclude:
    - test/dual/run_red_amber_green_test.rb
    - test/server/run_clang_ptrace_test.rb

Lint/RescueException:
  Exclude:
    - client/code/dispatcher.rb
    - client/code/rack_dispatcher.rb
    - code/dispatcher.rb
    - code/rack_dispatcher.rb
    - code/traffic_light.rb
    -

