AllCops:
    NewCops: enable

Style/FrozenStringLiteralComment:
  Exclude:
    - code/gnu_zip.rb
    - code/tarfile_writer.rb
    - test/test_base.rb

Lint/PercentStringArray:
  Exclude:
    - test/**/*

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - code/**/*
    - client/code/**/*
    - test/**/*

# I often give an inline expression a name for readability
Lint/UselessAssignment:
  Exclude:
    - code/**/*
    - test/**/*

Naming/VariableNumber:
  Exclude:
    - test/**/*

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - test/server/run_timed_out_test.rb

Style/Documentation:
  Exclude:
    - code/**/*
    - client/code/**/*
    - test/**/*

