AllCops:
  NewCops: enable
  Exclude:
    - test/**/*

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - source/server/**/*
    - source/client/**/*

Layout/LineLength:
  Exclude:
    - source/client/demo.rb

Lint/RescueException:
  Exclude:
    - source/*/dispatcher.rb
    - source/*/rack_dispatcher.rb
    - source/server/traffic_light.rb

Lint/UselessMethodDefinition:
  Exclude:
    - source/server/empty_binding.rb

Metrics/AbcSize:
  Exclude:
    - source/server/runner.rb
    - source/*/dispatcher.rb
    - source/server/context.rb
    - source/server/capture3_with_timeout.rb
    - source/client/demo.rb

Metrics/ClassLength:
  Exclude:
    - source/server/runner.rb
    - source/client/demo.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - source/*/dispatcher.rb
    - source/server/context.rb

Metrics/MethodLength:
  Exclude:
    - source/server/traffic_light.rb
    - source/server/tagged_image_name.rb
    - source/server/runner.rb
    - source/server/puller.rb
    - source/server/files_delta.rb
    - source/server/externals/bash_sheller.rb
    - source/*/dispatcher.rb
    - source/server/capture3_with_timeout.rb
    - source/client/demo.rb
    - source/server/home_files.rb

Metrics/ParameterLists:
  Exclude:
    - source/server/runner.rb

Metrics/PerceivedComplexity:
  Exclude:
    - source/server/context.rb

Style/Documentation:
  Exclude:
    - source/*/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - source/server/gnu_zip.rb
    - source/server/tarfile_writer.rb

Style/RedundantInitialize:
  Exclude:
    - source/server/prober.rb
