AllCops:
    NewCops: enable

Style/FrozenStringLiteralComment:
  Exclude:
    - code/gnu_zip.rb
    - code/tarfile_writer.rb
    - test/test_base.rb

Lint/PercentStringArray:
  Exclude:
    - test/**/*

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - code/**/*
    - client/code/**/*
    - test/**/*

# I often give an inline expression a name for readability
Lint/UselessAssignment:
  Exclude:
    - code/**/*
    - test/**/*

Naming/VariableNumber:
  Exclude:
    - test/**/*

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - test/server/run_timed_out_test.rb

Style/Documentation:
  Exclude:
    - code/**/*
    - client/code/**/*
    - test/**/*

Metrics/ParameterLists:
  Exclude:
    - code/runner.rb

Lint/EmptyBlock:
  Exclude:
    - test/dual/run_red_amber_green_test.rb
    - test/server/run_clang_ptrace_test.rb

Lint/RescueException:
  Exclude:
    - client/code/dispatcher.rb
    - client/code/rack_dispatcher.rb
    - code/dispatcher.rb
    - code/rack_dispatcher.rb
    - code/traffic_light.rb

Lint/UselessMethodDefinition:
  Exclude:
    - code/empty_binding.rb

Style/RedundantInitialize:
  Exclude:
    - code/prober.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*
    - code/traffic_light.rb
    - code/tagged_image_name.rb
    - code/runner.rb
    - code/puller.rb
    - code/files_delta.rb
    - code/externals/bash_sheller.rb
    - code/dispatcher.rb
    - code/capture3_with_timeout.rb
    - client/code/dispatcher.rb
    - client/code/demo.rb
    - code/home_files.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*


Metrics/ClassLength:
  Exclude:
    - test/**/*
    - code/runner.rb
    - client/code/demo.rb
  

