
services:

  client:
    platform: linux/amd64
    build:
      context: source/client
      args:
        - COMMIT_SHA
    image: ${CYBER_DOJO_RUNNER_CLIENT_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    user: ${CYBER_DOJO_RUNNER_CLIENT_USER}
    depends_on: [ server ]
    env_file: [ .env ]
    environment:
      - CONTEXT=client
      - SHOW_TEST_IDS=false
    read_only: true
    restart: no
    tmpfs: /tmp
    volumes:
      - ./source/client:/runner/source:ro
      - ./test:/runner/test/:ro

  server:
    platform: linux/amd64
    build:
      context: .
      args:
        - COMMIT_SHA
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    user: ${CYBER_DOJO_RUNNER_SERVER_USER}
    depends_on: [ languages-start-points ]
    env_file: [ .env ]
    environment:
      - CONTEXT=server
      - SHOW_TEST_IDS=false
    read_only: true
    restart: no
    tmpfs: /tmp
    volumes:
      - ./source/server:/runner/source/:ro
      - ./test:/runner/test/:ro
      - /var/run/docker.sock:/var/run/docker.sock

  languages-start-points:
    platform: linux/amd64
    image: ${CYBER_DOJO_LANGUAGES_START_POINTS}
    user: nobody
    env_file: [ .env ]
    read_only: true
    restart: no
    tmpfs: /tmp
