
fullnameOverride: "runner"

daemonSet: true

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: runner-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: File

containers:
  - name: runner
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: runner-tmp-dir
        mountPath: /tmp
        readOnly: false
      - mountPath: /var/run/docker.sock
        name: docker-socket
    resources:
      requests:
        cpu: 20m
        memory: 256Mi
      limits:
        memory: 1Gi
    livenessProbe:
      path: /alive?
    readinessProbe:
      path: /ready?

initContainers: {}

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
