
fullnameOverride: "runner"

daemonSet: true

initContainers: {}
envFromSecret: {}
nodeSelector: {}
affinity: {}
tolerations: []

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: runner-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: File

containers:
  - name: runner
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: runner-tmp-dir
        mountPath: /tmp
        readOnly: false
      - mountPath: /var/run/docker.sock
        name: docker-socket
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
      limits:
        memory: 768Mi
    livenessProbe:
      path: /alive
    readinessProbe:
      path: /ready
    env:
      CYBER_DOJO_USE_CONTAINERD: "true"
      CYBER_DOJO_PROMETHEUS: "true"
      CYBER_DOJO_RUNNER_PORT: "4597"
      # CYBER_DOJO_K8S_PORT: "19661"
