# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "runner"

replicaCount: 1

volumes:
  - name: runner-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: File

service:
  port: 4597

containers:
  - name: runner
    image: cyberdojo/runner
    tag: ""
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: runner-tmp-dir
        mountPath: /tmp
        readOnly: false
      - mountPath: /var/run/docker.sock
        name: docker-socket
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 4Gi
      livenessProbe:
        path: /sha
        port: 4597
      readinessProbe:
        path: /ready?
        port: 4597

initContainers: {}

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
