
fullnameOverride: "runner"

daemonSet: true

service:
  port: 4597
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4597"

volumes:
  - name: runner-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "64Mi"
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: File

containers:
  - name: runner
    image: cyberdojo/runner
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: runner-tmp-dir
        mountPath: /tmp
        readOnly: false
      - mountPath: /var/run/docker.sock
        name: docker-socket
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        cpu: 750m
        memory: 4Gi
    livenessProbe:
      path: /alive?
      port: 4597
    readinessProbe:
      path: /ready?
      port: 4597

initContainers: {}

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
