name: Base Image Update

on:
  workflow_dispatch:
    inputs:
      base_image_tag:
        description: "Image-Tag for cyberdojo/docker-base (short commit SHA - first 7 digits), eg d6830c0"
        required: true
      base_image_digest:
        description: "Image-Digest for cyberdojo/docker-base, eg 4be745df9..."
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      base_image:  ${{ steps.vars.outputs.base_image }}
      kosli_trail: ${{ steps.vars.outputs.kosli_trail }}
    steps:
      - name: Outputs
        id: vars
        run: | 
          TAG_WITH_DIGEST="${{ inputs.base_image_tag }}@sha256:${{ inputs.base_image_digest }}"          
          echo "base_image=cyberdojo/docker-base:${TAG_WITH_DIGEST}"        >> ${GITHUB_OUTPUT}
          echo "kosli_trail=base-image-update-${{ inputs.base_image_tag }}" >> ${GITHUB_OUTPUT}

  trigger:
    needs: [setup]
    uses: ./.github/workflows/main.yml
    with:
      BASE_IMAGE:  ${{ needs.setup.outputs.base_image }}
      KOSLI_TRAIL: ${{ needs.setup.outputs.kosli_trail }}
    secrets:
      SNYK_TOKEN:      ${{ secrets.SNYK_TOKEN }}
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}

