require_relative 'bash_sheller_stub'
require_relative 'daemon_stub'
require_relative 'rack_request_stub'
require_relative 'random_hex8_stub'
require_relative 'stdout_logger_spy'
require_relative 'threader_synchronous'
require_relative 'traffic_light_stub'
